### ISSUE TITLE
Data source?

### ISSUE THREAD

**Issue by yodahuang** [kikacaty/GRE-Helper#1]
I try to make a Pebble watch app on GRE, too. A problem I find is that there isn't exising json for 3000 GRE words. However, if I make the user to type in the words and Chinese explanations themselves, that process takes too long and is totally not worth it.

Contact me if you find a good solution!

**Comment by yodahuang** [comment]
Oh I actually find a json file for it...

**Comment by kikacaty** [comment]
Actually I was planning to use an [En translation API](https://www.wordsapi.com/) instead of saving all of the word. Or you can try to access some API to help auto complete when entering in. By the way, since apple just offer SDK for Siri, I also considering using voice detection.

**Comment by yodahuang** [comment]
The translation sure can use an API. The problem is that there isn't an API that gives you a **GRE** word every time you try to invoke it.
